"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import base64
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Só carrega o .env local fora da Vercel — lá as variáveis são injetadas
# direto no ambiente. Sem essa guarda, um .env que fosse parar no bundle do
# deploy (ex.: DJANGO_DEBUG="True" pra dev) sobrescreveria a config de
# produção. `load_dotenv` não sobrepõe variáveis já definidas, mas as que a
# Vercel NÃO define (como DJANGO_DEBUG) seriam lidas do arquivo.
if not os.environ.get("VERCEL"):
    load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]

# Chave pública RS256 usada para validar o access token emitido pelo gateway
# Next.js (ver comum/autenticacao.py). Só a chave pública circula por aqui —
# a privada fica exclusivamente no .env do Next.js.
JWT_ACCESS_PUBLIC_KEY = base64.b64decode(
    os.environ["JWT_ACCESS_PUBLIC_KEY_B64"]
).decode("utf-8")

# Emissor e audiência esperados no access token — precisam bater com o que o
# Next.js carimba (src/lib/token.ts: EMISSOR_TOKEN_ACESSO / AUDIENCIA_TOKEN_ACESSO).
JWT_ACCESS_ISSUER = "auth-gateway"
JWT_ACCESS_AUDIENCE = "auth-gateway-servicos"


# Hardening de produção (fora da Vercel / com DEBUG, fica tudo desligado pra
# não atrapalhar o dev local em http). A Vercel termina o TLS na edge e
# repassa via proxy, então o Django precisa confiar no header pra saber que a
# requisição original era https.
if not DEBUG:
    # A Vercel só serve https na borda; SECURE_SSL_REDIRECT fica de fora de
    # propósito (um 301 num POST do proxy viraria GET). O resto é barato e
    # sem risco pra uma API JSON.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 63072000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tarefas',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'comum.autenticacao.AutenticacaoJWT',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'comum.autenticacao.ProtegidoContraCsrf',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Não há FK real entre este serviço e o gateway Next.js, só o claim 'sub' do
# JWT como referência opaca de usuário. Local: Postgres próprio
# (autenticacao_dominio). Produção: mesma instância Supabase do Next.js, mas
# num schema próprio (DATABASE_SCHEMA=dominio) — a separação lógica de antes
# (bancos distintos), agora via schema.

DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get('DATABASE_URL') or f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}

_schema = os.environ.get('DATABASE_SCHEMA')
if _schema and DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    DATABASES['default'].setdefault('OPTIONS', {})
    # search_path com public no fim: as tabelas do serviço ficam em `dominio`
    # (primeiro da lista, então é onde `migrate` cria), e funções de extensão
    # que moram em `public` continuam resolvíveis.
    DATABASES['default']['OPTIONS']['options'] = f'-c search_path={_schema},public'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
