# Generated by Django 5.2.16 on 2026-07-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('usuario_id', models.CharField(max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
