# Generated by Django 5.2.17 on 2026-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='organizacao_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='organizacao_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
